import type { Metadata } from "next";
import { Metrophobic } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

const metrophobic = Metrophobic({
  variable: "--font-metrophobic",
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <Navbar />
      <html lang="en">
        <body className={`${metrophobic.variable} antialiased`}>
          {children}
        </body>
      </html>
    </>
  );
}
