import type { Metadata } from "next";
import { Bai_Jamjuree, Space_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";


const baiJamjuree = Bai_Jamjuree({
  subsets: ["latin"],
  variable: "--font-sans",
  weight: ["200", "300", "400", "500", "600", "700"],
});

const spaceMono = Space_Mono({
  subsets: ["latin"],
  variable: "--font-mono",
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <html
        lang="en"
        className={`${baiJamjuree.variable} ${spaceMono.variable} h-full`}
      >
        <body className="antialiased">
        {children}
        <Toaster />
      </body>
      </html>
    </>
  );
}
